/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'l.fedyszyn' at '3/27/17 9:20 AM' with Gradle 2.13
 *
 * @author l.fedyszyn, @date 3/27/17 9:20 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
